mysql:
  host: "localhost"
  port: 3306
  database: "ProjectManage"
  user: "root"
  password: "a123456"
  charset: "utf8mb3"
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: ""
  timeout: 5
  pool_size: 10
